name: Build & Release Installer

on:
  workflow_dispatch:
    inputs:
      release_version:
        description: 'Version (ex: v1.0.0)'
        required: true
        default: 'v1.0.0'

jobs:
  build:
    name: Build EXE with Inno Setup
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m venv venv
          venv\Scripts\activate
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller

      - name: Build Python app with PyInstaller
        run: |
          venv\Scripts\activate
          pyinstaller --onefile --windowed --icon=icon.ico .\autotheme.py 
          
      - name: Download and Install Inno Setup
        run: |
          Invoke-WebRequest -Uri "https://jrsoftware.org/download.php/is.exe" -OutFile "is.exe"
          Start-Process .\is.exe -ArgumentList "/VERYSILENT" -Wait

      - name: Compile Inno Setup Installer
        run: |
          $env:RELEASE_VERSION="${{ inputs.release_version }}"
          & "C:\Program Files (x86)\Inno Setup 6\ISCC.exe" "AutoThemeInstaller.iss"

      - name: Upload Setup EXE as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: AutoThemeSetup
          path: Output/AutoThemeInstaller_${{ inputs.release_version }}.exe

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          name: Release ${{ inputs.release_version }}
          tag_name: ${{ inputs.release_version }}
          files: Output/AutoThemeInstaller_${{ inputs.release_version }}.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}



